#docker build -f Dockerfile_1 --platform=linux/arm64 -t mpich-2-1 .

FROM ubuntu:22.04

ENV F_NAME=lab2_1.c
ENV N=4
RUN apt-get update && apt-get install -y \
    build-essential \
    mpich \
    && apt-get clean


WORKDIR /app

COPY ${F_NAME} .

CMD ["sh", "-c", "mpicc $F_NAME -o main && mpiexec -n $N ./main"]
